First draft of functional tests
opentelekomcloud/kontainer-engine-driver-otc pull request #23
Opened 2020-09-28 12:22 UTC by kucerakk

2020-09-28 13:05 UTC, gtema approved these changes

2020-09-28 13:21 UTC, gtema approved these changes

2020-09-28 13:40 UTC, gtema approved these changes

2020-09-28 13:58 UTC, vladimirhasko approved these changes

2020-09-28 14:15 UTC, vladimirhasko approved these changes

2020-09-28 14:35 UTC, vladimirhasko submitted a review, later dismissed

2020-09-29 06:45 UTC, vladimirhasko approved these changes

2020-09-29 07:09 UTC, vladimirhasko approved these changes

2020-09-29 08:41 UTC, gtema commented
recheck post

2020-09-29 09:11 UTC, gtema commented
recheck post

2020-09-29 13:34 UTC, vladimirhasko approved these changes

2020-09-29 13:44 UTC, vladimirhasko approved these changes

2020-09-29 13:57 UTC, vladimirhasko approved these changes

2020-09-29 14:44 UTC, vladimirhasko approved these changes

2020-09-29 17:47 UTC, gtema commented on roles/prepare-rancher-env/defaults/main.yml
> +rancher_driver_location: https://github.com/opentelekomcloud/kontainer-engine-driver-otc/releases/download/v0.2.1/kontainer-engine-driver-otc-0.2.1-linux-amd64.tgz
let's make this a variable coming from job (default points here, but job should be able to override it)

2020-10-02 22:07 UTC, outcatcher commented
I don't think, that this is a right location for the func tests. They should be triggered for PRs in both driver and UI. Besides they really blow this repo up.

2020-10-02 22:08 UTC, outcatcher requested changes
I don't think, that this is a right locationto keep func tests. They should be triggered for PRs in both driver and UI. Besides they really blow this repo up.

2020-10-07 08:56 UTC, vladimirhasko submitted a review, later dismissed

2020-10-07 09:12 UTC, vladimirhasko approved these changes

2020-10-07 11:00 UTC, vladimirhasko approved these changes

2020-10-07 11:58 UTC, vladimirhasko submitted a review, later dismissed

2020-10-07 13:03 UTC, vladimirhasko approved these changes

2020-10-07 13:35 UTC, vladimirhasko approved these changes

2020-10-08 06:16 UTC, vladimirhasko submitted a review, later dismissed

2020-10-08 10:29 UTC, vladimirhasko approved these changes

2020-10-08 10:52 UTC, vladimirhasko submitted a review, later dismissed

2020-10-08 13:51 UTC, gtema commented
recheck

2020-10-08 13:56 UTC, gtema commented
recheck

2020-10-08 17:15 UTC, gtema submitted a review, later dismissed
trigger post-review

2020-10-09 09:52 UTC, gtema commented
recheck

2021-04-08 06:38 UTC, outcatcher commented
Done in https://github.com/opentelekomcloud-infra/rancher-integration-tests

2021-04-08 06:38 UTC, closed without merging